name: Market Basket Analysis CI-CD

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]


jobs:

  test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Market Basket Analysis
        run: |
          python main.py


  docker-build-push:
    needs: test
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build --platform linux/amd64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/market-basket-analysis:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/market-basket-analysis:latest


  deploy:
    needs: docker-build-push
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to Render
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"